### ISSUE TITLE
ESLint and Typescript compatibility

### ISSUE THREAD

**Issue by moncapitaine** [progwise/timebook#973]

**Comment by YohannesTesfay** [comment]
This issue has been postponed because updates for Next.js and React (#1002) had to be done beforehand.
Useful links:
- [https://stackoverflow.com/questions/79128326/eslint-9-is-not-working-properly-with-next-15](url)
- [https://nextjs.org/docs/app/api-reference/config/eslint](url)
- [https://github.com/vercel/next.js/issues/64409](url)
- [https://nextjs.org/docs/app/building-your-application/upgrading/version-14](url)
